#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 11
bspc config top_padding -9

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

# Set floating windows
bspc rule -a imv state = floating
bspc rule -a Thunar state = floating
bspc rule -a kitty state = floating

# Set all floating
bspc rule -a '*' state=floating
# Make some exceptions
bspc rule -a firefox state=tiled

# Carry zathura to top!
bspc rule -a Zathura layer = above

# Center windows
center = true

# Focus on hover
bspc config focus_follows_pointer true

# Outline colors
bspc config focused_border_color "#A7C080"
bspc config normal_border_color "#425047"
bspc config urgent_border_color "#e67e80"

# Keyboardeyboard toggle
setxkbmap -option grp:alt_shift_toggle us,tr
setxkbmap -option caps:escape_shifted_capslock

# AutoStart applications
sxhkf &
picom --config $HOME/.config/picom/picom.conf &
NetworkManager &
dunst &
~/.config/polybar/launch.sh &
~/.fehbg &
xfce4-power-manager &
/usr/lib/xfce-polkit/xfce-polkit &

# Fix cursor
xsetroot -cursor_name left_ptr
